export type BacklinkOpportunity = { id: number; title: string; url?: string; status: 'Done' | 'Open' | 'To check' | 'No action'; finding: string; action: string; note?: string; links?: { name: string; url: string }[] };
export const opportunities: BacklinkOpportunity[] = [
 {id:1,title:'BuildSteel / SFIA: new story pitch (Palisades rebuild with Wheeler Residential, IBS 2027, October 11 event)',status:'Open',finding:'New coverage can introduce Wheeler Residential’s current work without changing historical articles.',action:'Pitch a new story about Wheeler Residential’s current work.'},
 {id:7,title:'YellowPages, Superpages and DexKnows',links:[{name:'YellowPages',url:'https://www.yellowpages.com/'},{name:'Superpages',url:'https://www.superpages.com/'},{name:'DexKnows',url:'https://www.dexknows.com/'}],status:'Open',finding:'wheelersteelsupply.com and Don’s older site are listed. Wheeler Residential Steel Supply is not.',action:'Create listings with consistent name, address and phone.'},
 {id:8,title:'Link from Don’s older website',url:'http://donwheelerconstruction.com/',status:'Open',finding:'No mention of the new website on the homepage or press page.',action:'Add a plain link to getwheelersteel.com. Do not redirect the domain as part of this work.'},
 {id:9,title:'Additional business directories',status:'Open',finding:'No listings found for the brand or phone on The Blue Book, Houzz, BuildZoom, Bing Places, Apple Business Connect, Yelp or BBB.',action:'Create listings using consistent business details.',links:[{name:'The Blue Book',url:'https://www.thebluebook.com/'},{name:'Houzz',url:'https://www.houzz.com/'},{name:'BuildZoom',url:'https://www.buildzoom.com/'},{name:'Bing Places',url:'https://www.bingplaces.com/'},{name:'Apple Business Connect',url:'https://businessconnect.apple.com/'},{name:'Yelp',url:'https://www.yelp.com/'},{name:'BBB',url:'https://www.bbb.org/'}]},
 {id:10,title:'SFIA member directory',url:'https://sfia.memberclicks.net/member-directory',status:'Open',finding:'Confirmed: Wheeler Residential Steel Supply is not listed in the SFIA member directory.',action:'Confirm membership eligibility and arrange a directory listing.'},
 {id:11,title:'Building Industry Association of Southern California',url:'https://biasc.org/meet-our-members/',status:'To check',finding:'Wheeler Residential Steel Supply is not listed in the member directory.',action:'Consider membership in relation to builder outreach.'},
 {id:12,title:'Palisades and Altadena rebuild resources',status:'Open',finding:'The existing Palisades Rebuild Partners listing provides a relevant example.',action:'Research similar directories and request appropriate listings.',note:'Research list to build'},
 {id:13,title:'International Builders’ Show 2027 PR',url:'https://www.buildersshow.com/Search/Exhibitor.aspx?id=1533073&year=2027',status:'Open',finding:'The exhibitor listing already exists.',action:'Announce the exhibit to relevant trade media.'},
 {id:14,title:'NBC4: Palisades home rebuilt with steel',status:'To check',finding:'NBC4 covered a steel-framed Palisades rebuild. Wheeler is not named.',action:'Confirm the project and company involved at the time. Keep historical coverage accurate; consider new coverage of current work.'},
 {id:15,title:'Manufacturer, architect and builder partner pages',status:'Open',finding:'Potential credit requests depend on Wheeler’s project and partner list.',action:'Ask relevant partners to credit Wheeler as framing supplier.',note:'Partner page links pending'},
 {id:16,title:'Trade media and journalist requests',status:'Open',finding:'The audit found no coverage of the new brand. Targets include Builder, JLC, Fine Homebuilding, Construction Dive, Qwoted and Featured.',action:'Position Don as an expert source on noncombustible framing.',note:'Outreach targets and links to prepare'},
 {id:18,title:'Google Search Console',url:'https://search.google.com/search-console',status:'To check',finding:'A Google verification record is present in the domain’s DNS, so Search Console is likely already set up. Access is still needed.',action:'Send access to Miguel.'},
 {id:19,title:'Social profiles (LinkedIn, Instagram, Facebook, Pinterest)',status:'Open',finding:'No social profiles are linked from the website, and its structured data lists only CFSEI. Check for existing profiles before creating duplicates.',action:'Confirm or create consistent company profiles, link them in the site footer and add their URLs to the Organization schema sameAs list.'},
 {id:2,title:'CFSEI Expo 2026 session page',url:'https://www.cfsei.org/building-for-the-21st-century--noncombustible-construction-with-cold-formed-steel',status:'No action',finding:'Historical coverage names the company Don worked with at the time.',action:'A link to Wheeler’s current site would be valuable, but this page was accurate at the time.'},
 {id:3,title:'BuildSteel: 2026 CFSEI Expo speaker lineup',url:'https://buildsteel.org/news/cfsei-announces-speakers-for-the-2026-cfsei-expo-in-long-beach/',status:'No action',finding:'Historical coverage names the company Don worked with at the time.',action:'A link to Wheeler’s current site would be valuable, but this page was accurate at the time.'},
 {id:4,title:'BuildSteel: Building for Fire',url:'https://buildsteel.org/news/building-for-fire-how-cold-formed-steel-is-changing-noncombustible-construction/',status:'No action',finding:'Historical coverage names the company Don worked with at the time.',action:'A link to Wheeler’s current site would be valuable, but this page was accurate at the time.'},
 {id:5,title:'BuildSteel: 2024 CFSEI Expo preview',url:'https://buildsteel.org/news/previewing-the-2024-cfsei-expo/',status:'No action',finding:'Historical coverage names the company Don worked with at the time.',action:'A link to Wheeler’s current site would be valuable, but this page was accurate at the time.'},
 {id:6,title:'Google Business Profile',status:'Done',finding:'Google Business Profile is already in place.',action:'Update the profile with recent project photos and keep business details, opening hours and the website link accurate.'}
];
